#!/bin/sh

RU="$(cat /etc/enigma2/settings | grep  'config.osd.language=ru_RU')"
LANG='config.osd.language=ru_RU'
if [  $LANG == $RU ]  2>/dev/null; then  2>/dev/null
	echo  " "
    echo  "Примеры профилей (только для ЕТхх00)..."
	echo  " "
	echo  "****************************************************"
	echo  "Название профиля 21:9"
	echo  "Использовать режим растяжения (3D контент) нет"
	echo  "Соотношение сторон 16:9"
	echo  "Лево 35"
	echo  "Ширина 650"
	echo  "Вверх 45"
	echo  "Высота 486"
	echo  "****************************************************"
	echo  " "
	echo  "****************************************************"
	echo  "Название профиля 4:3"
	echo  "Использовать режим растяжения (3D контент) нет"
	echo  "Соотношение сторон 16:9"
	echo  "Лево 0"
	echo  "Ширина 720"
	echo  "Вверх 50"
	echo  "Высота 486"
	echo  "*****************************************************"
	echo  " "
	echo  "****************************************************"
	echo  "Название профиля 14:9"
	echo  "Использовать режим растяжения (3D контент) нет"
	echo  "Соотношение сторон 16:9 всегда"
	echo  "Лево 0"
	echo  "Ширина 720"
	echo  "Вверх 35"
	echo  "Высота 496"
	echo  "*****************************************************"
	echo  " "
	echo  "*****************************************************"
	echo  "Название профиля Full Pan&Scan"
	echo  "Использовать режим растяжения (3D контент) нет"
	echo  "Соотношение сторон 16:9"
	echo  "Лево 100"
	echo  "Ширина 520"
	echo  "Вверх 0"
	echo  "Высота 576"
	echo  "---------------------------------------------------------------------------"
	echo  "Внимание!Для этого профиля:"
	echo  "Аудио/Видео->Показывать >16:9 контент как-> Pan&Scan"
	echo  "---------------------------------------------------------------------------"
	echo  "****************************************************"
 else
	echo  " "
	echo  "Examples profiles (only ETxx00) ..."
	echo  " "
	echo  "****************************************************"
	echo  "Profile Name 21:9"
	echo  "Use Video Stretch (3D content) no"
	echo  "Aspect Ratio 16:9"
	echo  "Video Left 35"
	echo  "Video Width 650"
	echo  "Video Top 45"
	echo  "Video Height 486"
	echo  "***************************************************"
	echo  " "
	echo  "***************************************************"
	echo  "Profile Name 4:3"
	echo  "Use Video Stretch (3D content) no"
	echo  "Aspect Ratio 16:9"
	echo  "Video Left 0"
	echo  "Video Width 720"
	echo  "Video Top 50"
	echo  "Video Height 486"
	echo  "****************************************************"
	echo  " "
	echo  "***************************************************"
	echo  "Profile Name 14:9"
	echo  "Use Video Stretch (3D content) no"
	echo  "Aspect Ratio 16:9 always"
	echo  "Video Left 0"
	echo  "Video Width 720"
	echo  "Video Top 35"
	echo  "Video Height 496"
	echo  "****************************************************"
	echo  " "
	echo  "****************************************************"
	echo  "Profile Name Full Pan&Scan"
	echo  "Use Video Stretch (3D content) no"
	echo  "Aspect Ratio 16:9"
	echo  "Video Left 100"
	echo  "Video Width 520"
	echo  "Video Top 0"
	echo  "Video Height 576"
	echo  "---------------------------------------------------------------------------"
	echo  "Attention!For this profile:"
	echo  "A/V Settings->Display 16:9 content as-> Pan&Scan"
	echo  "---------------------------------------------------------------------------"
	echo  "****************************************************"
fi